services:
  backend:
    image: ghcr.io/kon-drees/fake-news-detector-backend:latest
    env_file:
      - ./.env.prod
    restart: always
    expose:
      - "8000"

  frontend:
    image: ghcr.io/kon-drees/fake-news-detector-frontend:latest
    depends_on:
      - backend
    restart: always
    ports:
      - "80:80"