[project]
name = "fake-news-detector"
version = "0.1.0"
description = "Fake News Detection"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.121.1",
    "pandas>=2.3.3",
    "pydantic-settings>=2.12.0",
    "pymongo>=4.15.4",
]
